# BUILD STAGE
FROM node:20-alpine3.19 as builder

WORKDIR /app 
COPY package.json ./

RUN npm install

COPY tsconfig.json nodemon.json tsoa.json build-script.js ecosystem.config.js ./

COPY src ./src

FROM node:20-alpine3.19

WORKDIR /app 

COPY package.json ./
RUN npm install --only=production
COPY --from=builder /app/build/ .
EXPOSE 3000
CMD [ "node","server.js" ]