version: '3.8' # Specifies the version of the Docker Compose file format

services:
  express-server:
    # Defines the service for the Express server
    container_name: my-dev-app # Name of the container for easier identification
    build:
      context: . # Context path for the build process (current directory)
      dockerfile: Dockerfile.dev # Specifies the Dockerfile to use for building the image
    restart: always # Automatically restart the container if it stops
    ports:
      - 4000:3000 # Maps port 3000 in the container to port 4000 on the host
    env_file: ./src/configs/.env.development # Load environment variables from the specified file
    environment:
      - DOCKER_ENV=true # Sets an environment variable indicating that the app is running in Docker
    volumes:
      - ./src:/app/src # Mounts the local src directory to /app/src in the container for hot reloading

  mongo_db:
    # Defines the service for the MongoDB database
    image: mongo # Uses the official MongoDB image from Docker Hub
    ports:
      - "27017:27017" # Maps port 27017 in the container to port 27017 on the host
    environment:
      MONGO_INITDB_ROOT_USERNAME: rong # Sets the root username for MongoDB
      MONGO_INITDB_ROOT_PASSWORD: 12345678 # Sets the root password for MongoDB
      MONGO_INITDB_ROOT_DATABASE: demoDocker # Specifies the initial database to create
    volumes:
      - mongodb_data:/data/db # Persists MongoDB data using a named volume

volumes:
  mongodb_data: # Defines a named volume for MongoDB data persistence
